[build]
target = "riscv32ec-unknown-none-elf"

[unstable]
build-std = ["core", "compiler_builtins"]

[target.riscv32ec-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

#runner = "wlink -v flash --enable-sdi-print"
runner = "wlink -v flash"
